# Generated by Django 4.1.13 on 2024-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionId', models.CharField(max_length=100, null=True)),
                ('CreatedBy', models.CharField(max_length=70, null=True)),
                ('CreatedTime', models.DateTimeField(null=True)),
                ('ReviewedBy', models.CharField(max_length=70, null=True)),
                ('ReviewedTime', models.DateTimeField(null=True)),
                ('Approved', models.CharField(max_length=1, null=True)),
                ('Last_Updated', models.DateTimeField(null=True)),
                ('Comments', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'questioninfo',
            },
        ),
    ]
