# Generated by Django 4.1.13 on 2024-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('email', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=70, null=True)),
            ],
            options={
                'db_table': 'login_data',
            },
        ),
    ]
